fun main() {
    println("Phrase a traduire")
var traduire= readLine()!!.split(' ')
    println(translate(traduire.toString()))
}


fun translate(phrase: String): String {
val motsFR = arrayOf(
"ne pas aimer",
"n\'aime pas",
"les problèmes",
"et",
"aime",
"aimer",
"je vais à",
"je vais a",
"école",
"l\'école",
"ecole",
"l\'ecole",
"élève",
"eleve",
"je pars",
"au",
"marché",
"oui",
"non",
"écris",
"écrit",
"écrivons",
"écrivez",
"écrivont",
"je suis malade",
"la maladie",
"maladie",
"malade",
"Les malades",
"aller quelques part",
"quelques part",
"aller",
"partir",
"chapitre",
"verset",
"versets",
"bible",
"bibles",
"famille",
"tout d\'abord",
"je remercie",
"je te remercie",
"Dieu",
"travail ",
"cours",
"j\'adresse",
"depuis",
"Adam",
"promesse",
"le nouveau testament",
"ancien testament",
"allié ",
"politique",
"ouvrir sa bouche",
"écarter",
"semence",
"graine",
"semis",
"avocat",
"Abraham",
"céder à",
"céder",
"annuler",
"prendre",
"veux",
"veut",
"voulons",
"voulez",
"veulent",
"voulais",
"voulais",
"voulait",
"voulions",
"vouliez",
"voulaient",
"voulu",
"prends",
"prend",
"prenons",
"prenez",
"prennent",
"prendrai",
"prendras",
"prendra",
"prendrons",
"prendrez",
"prendront",
"bouger quelque chose ",
"bouger quelqu\'un",
"quelqu\'un",
"introduction",
"La parole",
"problème",
"gens",
"les gens du monde",
"monde",
"terre",
"parole",
"afrique",
"le premier fils",
"la première fille",
"première fille",
"premier fils",
"examen",
"coutume",
"tradition",
"pratique",
"signe clinique",
"dimanche",
"mercredi",
"avec",
"ail",
"Porte-monnaie",
"oignon",
"notre",
"amen",
"intelligence",
"intelligent",
"il est intelligent",
"elle est intelligente",
"l\'homme blanc",
"ambassade",
"l\'ambassade",
"ambassadeur",
"année",
"populations",
"populations",
"les gens",
"connaissance",
"la connaissance",
"le savoir",
"expérience",
"la science",
"science",
"l\'expérience",
"aujourd\'hui",
"demain",
"hier",
"avant-hier",
"après-demain",
"enseigner",
"la langue",
"mouton",
"grand",
"petit",
"baiser",
"baise",
"faire l\'amour",
"coucher",
"chevre",
"chévre",
"chèvre",
"devenir",
"repos",
"je mange",
"mange",
"Nom",
"salut",
 "bonjour", 
 "bonne nuit",
  "comment tu vas",
  " je vais bien", 
  "je vais bien et toi",
   " ",
    "la joie",
    "joie",
    "le bonheur",
     "bonheur",
     "famine",
      "la famine",
      "la nourriture",
      "nourriture",
      "l'eau",
      "boire de l'eau",
      "blanc",
      "blanche",
      "noir",
       "noire",
       "rouge",
       "vendre",
       "manger",
       "l'esprit",
       "voleur",
       "natte",
       "sol",
       "terre",
       "pays",
       "habit",
       "maison",
       "mouches",
       "mouche",
       "arraignée",
       "arraignées",
       "montagne",
       "doucement",
       "paresseux",
       "un fou",
       "fou",
       "villageois",
       "enfants",
       "enfants",
       "femme",
       "homme",
       "maman",
       "papa",
       "grand frère",
       "grande soeur",
       "oncle",
       "Oncle",
       "tante",
       "Tante",
       "chat",
       "chambre",
       "brulé",
       "cuisiner",
       "moi",
       "je",
       "toi",
       "tu",
       "lui",
       "il",
       "elle",
       "nous",
       "nous",
       "vous",
       "vous",
       "eux",
       "ils",
       "elles",
       "j'ai",
       "tu as",
       "il a",
       "elle a",
       "nous avons",
       "vous avez",
       "ils ont",
       "elles ont",
       "je suis",
        "tu es",
         "il est",
         "elle est",
         "nous sommes",
         "vous êtes",
         "vous etes",
         "ils sont",
         "elles sont",
         "sa maison",
         "ma maison",
         "son mari",
         "mon mari",
         "ma femme",
         "sa femme"
         );
 val motsFB = arrayOf(
    "na ",
    "yida",
    "haala",
    "be",
    "yidi",
    "hidigo",
    "mi done yah",
    "mi done yah","djanguirdé","djanguirdé","djanguirdé","djanguirdé","binguel djanduirdé","binguel djanduirdé","mi done dilla","a","loumo","ohoo","kaÏ","wildi","wildi","wilden","wildéh","wildan","mi nyaoudo","nyaou","nyaou","nyaoudo","nyaoubéh","yahogo bébelle","bébelle","yahogo","dinlégo","sourate","aya","aya","deftéré","deftéré","légnol","tawon","mi yotti ","mi yotti ma","Allah","cougal","darséré","mi done wiya","tigame","Aadama ","aadi","Aadi Keyri ","Aadi Kiinndi","aadondiraaɗo ","politikki","maboutougo  hounndouko","ndassou","aawdiiri","aawdiiri","aawdiiri","aboka","Abraama","atchounou","atchounougo","facitougo","hossogo","hidi","hidi","hidi","hidi","hidi","hidi noo","hidi noo","hidi noo","hidi noo","hidi noo","hidi go","hidi","hossou","hossou","hossou","hossou","hossou","hossann","hossann","hossann","hossann","hossann","hossann","dimbinogo coudjé","dimbinogo goddo","goddo","fouddogo","hala","haala","yimbeh","yimbeh douniya","douniya","lesdi","hala","afiriki","afo","afo","afo","afo","agijame","al\'aada ","al\'aada ","al\'aada","nyaou","alat","alarba","bé","albatché","possa","tiniereh","notre","amen","andal","faamou","ho mari faamou","ho mari faamou","nassara","ammbasad","ammbasad","maoudo ammbasad","doubi","yimbeh","yimbeh","yimbeh","faamu","faamu","hakkillo","paamu","andal","andal","paamu","handeh","djangoo","kennya","hesisi kennya","fappi django","janngindeh","woondeh","baala","maanga","petelle","baaldal","baaldal","baaldal","waalougo","mbewa","mbewa","mbewa","wartogo","sioutogo","mi done gnama","gnama","Indé","misani", " awali djam ", "djam wala", "noy", "wala ", "wala an bo"," ","hayrou","hayrou","seyo","seyo","welo","welo","gnamdou","gnamdou","ndiyam","yarogo ndiyam","danédjoum","danédjoum","balédjoum","balédjoum","bodédjoum","sippougo","gnamougo","hakkilo","goudjo","dago","lesdi","lesdi","wouro","loumché","saaré","boubii","boubii","tchaytchay","tchaytchay","hosséré","be hakkilo","mbassedjo","guinnado","guinnado","kaywédjo","bikkone","binguel","debbo","gorgo","dada","baba","hamma","adda","kawou","bappa","yapendo","goggo","patourou","soudou","wouli","defougo","mine","mi","ane","a","kanko","o","o","ene","enen","one","onon","kambé","bé","bé","mi mari","a mari","o mari","o mari","ene mari","one mari","bé mari","bé mari", "mi done","a done","o done","o done","ene done","one done","one done","bé done","bé done","saaré mako","saaré am", "gorgo mako","gorgo am","debbo am","debbo mako");

  var result = phrase
    for (i in motsFR.indices) {
        result = result.replace(motsFR[i], motsFB[i])
        //replace(motsFR[i], motsFB[i])
    }
    return result
}
